-- Vayvora AI Calling — initial schema
--
-- Covers the tables defined in the product documentation (§23), grouped by
-- domain. The organization is the root entity: every tenant-scoped table
-- carries organization_id and cascades from it, which is what makes the
-- isolation requirement in §33 enforceable at the database level.
--
-- Identifiers are UUIDs generated by the application. They travel in events
-- and webhook payloads, where sequential ids would leak tenant volume.
--
-- Money is stored in minor units (paise) as BIGINT. Never floating point.
-- Timestamps are TIMESTAMPTZ and written in UTC.

-- ---------------------------------------------------------------------------
-- Identity and organization
-- ---------------------------------------------------------------------------

CREATE TABLE organizations (
    id                        VARCHAR(36)  PRIMARY KEY,
    name                      VARCHAR(255) NOT NULL,
    slug                      VARCHAR(255) NOT NULL UNIQUE,
    primary_contact_email     VARCHAR(255),
    timezone                  VARCHAR(64)  NOT NULL DEFAULT 'Asia/Kolkata',
    default_language          VARCHAR(16)  NOT NULL DEFAULT 'en-IN',
    status                    VARCHAR(32)  NOT NULL DEFAULT 'TRIAL',
    ai_disclosure_enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    record_calls              BOOLEAN      NOT NULL DEFAULT TRUE,
    redact_pii                BOOLEAN      NOT NULL DEFAULT TRUE,
    recording_retention_days  INTEGER      DEFAULT 90,
    created_at                TIMESTAMPTZ  NOT NULL,
    updated_at                TIMESTAMPTZ  NOT NULL
);

CREATE TABLE users (
    id               VARCHAR(36)  PRIMARY KEY,
    organization_id  VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    email            VARCHAR(255) NOT NULL UNIQUE,
    -- BCrypt hash. The plaintext password is never stored.
    password_hash    VARCHAR(255) NOT NULL,
    first_name       VARCHAR(255) NOT NULL,
    last_name        VARCHAR(255) NOT NULL,
    role             VARCHAR(32)  NOT NULL DEFAULT 'AGENT',
    status           VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    last_active_at   TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_users_org ON users(organization_id);

CREATE TABLE roles (
    id               VARCHAR(36)  PRIMARY KEY,
    organization_id  VARCHAR(36)  REFERENCES organizations(id) ON DELETE CASCADE,
    name             VARCHAR(64)  NOT NULL,
    description      VARCHAR(255),
    is_system        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_role_org_name UNIQUE (organization_id, name)
);

CREATE TABLE permissions (
    id           VARCHAR(36) PRIMARY KEY,
    code         VARCHAR(96) NOT NULL UNIQUE,
    description  VARCHAR(255),
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL
);

CREATE TABLE role_permissions (
    id             VARCHAR(36) PRIMARY KEY,
    role_id        VARCHAR(36) NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id  VARCHAR(36) NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    created_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_role_perm UNIQUE (role_id, permission_id)
);

-- Membership is its own table so a user can later belong to more than one
-- organization without reshaping users.
CREATE TABLE organization_users (
    id               VARCHAR(36) PRIMARY KEY,
    organization_id  VARCHAR(36) NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id          VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role             VARCHAR(32) NOT NULL,
    invited_at       TIMESTAMPTZ,
    joined_at        TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_org_user UNIQUE (organization_id, user_id)
);

-- Refresh tokens are persisted as SHA-256 digests so a session can be revoked
-- before its natural expiry; the raw token is never stored.
CREATE TABLE refresh_tokens (
    id          VARCHAR(36)  PRIMARY KEY,
    user_id     VARCHAR(36)  NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(128) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_refresh_user ON refresh_tokens(user_id);

-- ---------------------------------------------------------------------------
-- AI agents
-- ---------------------------------------------------------------------------

CREATE TABLE ai_voices (
    id            VARCHAR(36)  PRIMARY KEY,
    code          VARCHAR(64)  NOT NULL UNIQUE,
    display_name  VARCHAR(255) NOT NULL,
    gender        VARCHAR(16)  NOT NULL,
    locale        VARCHAR(16)  NOT NULL,
    provider      VARCHAR(64),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL
);

-- organization_id NULL marks a platform-provided tool available to everyone.
CREATE TABLE ai_tools (
    id                     VARCHAR(36)  PRIMARY KEY,
    organization_id        VARCHAR(36)  REFERENCES organizations(id) ON DELETE CASCADE,
    code                   VARCHAR(96)  NOT NULL,
    display_name           VARCHAR(255) NOT NULL,
    description            VARCHAR(512),
    parameters_schema      TEXT,
    requires_confirmation  BOOLEAN      NOT NULL DEFAULT FALSE,
    active                 BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at             TIMESTAMPTZ  NOT NULL,
    updated_at             TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_tool_org_code UNIQUE (organization_id, code)
);

CREATE TABLE ai_agents (
    id                VARCHAR(36)  PRIMARY KEY,
    organization_id   VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name              VARCHAR(255) NOT NULL,
    agent_type        VARCHAR(48)  NOT NULL,
    status            VARCHAR(32)  NOT NULL DEFAULT 'DRAFT',
    published_version INTEGER,
    current_version   INTEGER      NOT NULL DEFAULT 1,
    created_by        VARCHAR(36),
    published_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_agent_org ON ai_agents(organization_id);
CREATE INDEX idx_agent_status ON ai_agents(organization_id, status);

-- An immutable snapshot of an agent configuration. List-valued fields are
-- comma-separated text: they are small, always read whole, never queried by
-- element.
CREATE TABLE ai_agent_versions (
    id                             VARCHAR(36) PRIMARY KEY,
    organization_id                VARCHAR(36) NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    agent_id                       VARCHAR(36) NOT NULL REFERENCES ai_agents(id) ON DELETE CASCADE,
    version                        INTEGER     NOT NULL,
    state                          VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    languages                      VARCHAR(255),
    voice_id                       VARCHAR(36),
    personality                    VARCHAR(255),
    system_prompt                  TEXT,
    knowledge_base_id              VARCHAR(36),
    enabled_tools                  VARCHAR(1024),
    max_call_minutes               INTEGER     NOT NULL DEFAULT 15,
    calling_window_start           VARCHAR(8)  DEFAULT '09:00',
    calling_window_end             VARCHAR(8)  DEFAULT '20:00',
    handoff_on_request             BOOLEAN     NOT NULL DEFAULT TRUE,
    handoff_on_negative_sentiment  BOOLEAN     NOT NULL DEFAULT TRUE,
    handoff_on_billing_dispute     BOOLEAN     NOT NULL DEFAULT FALSE,
    published_at                   TIMESTAMPTZ,
    published_by                   VARCHAR(36),
    created_at                     TIMESTAMPTZ NOT NULL,
    updated_at                     TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_agent_version UNIQUE (agent_id, version)
);
CREATE INDEX idx_agent_version_agent ON ai_agent_versions(agent_id);

CREATE TABLE ai_prompts (
    id               VARCHAR(36) PRIMARY KEY,
    organization_id  VARCHAR(36) NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    agent_id         VARCHAR(36) NOT NULL REFERENCES ai_agents(id) ON DELETE CASCADE,
    version          INTEGER     NOT NULL,
    state            VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    content          TEXT        NOT NULL,
    change_note      VARCHAR(512),
    created_by       VARCHAR(36),
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_prompt_agent ON ai_prompts(agent_id);

-- ---------------------------------------------------------------------------
-- Knowledge base and RAG
-- ---------------------------------------------------------------------------

CREATE TABLE knowledge_bases (
    id               VARCHAR(36)  PRIMARY KEY,
    organization_id  VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name             VARCHAR(255) NOT NULL,
    description      VARCHAR(512),
    embedding_model  VARCHAR(96)  DEFAULT 'text-embedding-3-small',
    chunk_size       INTEGER      NOT NULL DEFAULT 800,
    chunk_overlap    INTEGER      NOT NULL DEFAULT 120,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_kb_org ON knowledge_bases(organization_id);

CREATE TABLE knowledge_documents (
    id                 VARCHAR(36)   PRIMARY KEY,
    organization_id    VARCHAR(36)   NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    knowledge_base_id  VARCHAR(36)   NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    title              VARCHAR(512)  NOT NULL,
    source_type        VARCHAR(16)   NOT NULL,
    source_uri         VARCHAR(1024),
    size_bytes         BIGINT,
    status             VARCHAR(32)   NOT NULL DEFAULT 'QUEUED',
    chunk_count        INTEGER       NOT NULL DEFAULT 0,
    error_message      VARCHAR(1024),
    indexed_at         TIMESTAMPTZ,
    uploaded_by        VARCHAR(36),
    created_at         TIMESTAMPTZ   NOT NULL,
    updated_at         TIMESTAMPTZ   NOT NULL
);
CREATE INDEX idx_kdoc_kb ON knowledge_documents(knowledge_base_id);
CREATE INDEX idx_kdoc_org ON knowledge_documents(organization_id);
CREATE INDEX idx_kdoc_status ON knowledge_documents(knowledge_base_id, status);

CREATE TABLE knowledge_chunks (
    id               VARCHAR(36) PRIMARY KEY,
    organization_id  VARCHAR(36) NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    document_id      VARCHAR(36) NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
    ordinal          INTEGER     NOT NULL,
    content          TEXT        NOT NULL,
    token_count      INTEGER,
    metadata         TEXT,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_chunk_doc_ordinal UNIQUE (document_id, ordinal)
);
CREATE INDEX idx_chunk_doc ON knowledge_chunks(document_id);

-- Vectors live in their own table so the embedding model can be swapped and
-- re-run without re-parsing source documents. A pgvector column is the
-- intended production representation; TEXT keeps this migration portable.
CREATE TABLE knowledge_embeddings (
    id               VARCHAR(36) PRIMARY KEY,
    organization_id  VARCHAR(36) NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    chunk_id         VARCHAR(36) NOT NULL UNIQUE REFERENCES knowledge_chunks(id) ON DELETE CASCADE,
    model            VARCHAR(96) NOT NULL,
    dimensions       INTEGER     NOT NULL,
    vector           TEXT,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL
);

-- ---------------------------------------------------------------------------
-- Telephony
-- ---------------------------------------------------------------------------

CREATE TABLE telephony_providers (
    id            VARCHAR(36)  PRIMARY KEY,
    code          VARCHAR(64)  NOT NULL UNIQUE,
    display_name  VARCHAR(255) NOT NULL,
    gateway_uri   VARCHAR(512),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL
);

CREATE TABLE phone_numbers (
    id                  VARCHAR(36) PRIMARY KEY,
    organization_id     VARCHAR(36) NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    e164                VARCHAR(24) NOT NULL UNIQUE,
    label               VARCHAR(128),
    provider_id         VARCHAR(36) REFERENCES telephony_providers(id),
    assigned_agent_id   VARCHAR(36) REFERENCES ai_agents(id) ON DELETE SET NULL,
    direction           VARCHAR(16) NOT NULL DEFAULT 'BOTH',
    monthly_cost_minor  BIGINT,
    active              BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_phone_org ON phone_numbers(organization_id);

-- ---------------------------------------------------------------------------
-- Contacts, companies and leads
-- ---------------------------------------------------------------------------

CREATE TABLE companies (
    id               VARCHAR(36)  PRIMARY KEY,
    organization_id  VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name             VARCHAR(255) NOT NULL,
    industry         VARCHAR(128),
    website          VARCHAR(255),
    employee_count   INTEGER,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_company_org ON companies(organization_id);

CREATE TABLE contacts (
    id                  VARCHAR(36)  PRIMARY KEY,
    organization_id     VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    first_name          VARCHAR(255) NOT NULL,
    last_name           VARCHAR(255),
    phone               VARCHAR(24)  NOT NULL,
    email               VARCHAR(255),
    company_id          VARCHAR(36)  REFERENCES companies(id) ON DELETE SET NULL,
    -- Denormalized for list views that would otherwise join on every row.
    company_name        VARCHAR(255),
    preferred_language  VARCHAR(16),
    lead_score          INTEGER      NOT NULL DEFAULT 0,
    lead_band           VARCHAR(16)  NOT NULL DEFAULT 'LOW',
    lead_status         VARCHAR(32)  NOT NULL DEFAULT 'NEW',
    next_action         VARCHAR(255),
    owner_user_id       VARCHAR(36)  REFERENCES users(id) ON DELETE SET NULL,
    last_contacted_at   TIMESTAMPTZ,
    do_not_call         BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_contact_org_phone UNIQUE (organization_id, phone)
);
CREATE INDEX idx_contact_org ON contacts(organization_id);
CREATE INDEX idx_contact_phone ON contacts(phone);
CREATE INDEX idx_contact_score ON contacts(organization_id, lead_score);

CREATE TABLE leads (
    id                 VARCHAR(36)   PRIMARY KEY,
    organization_id    VARCHAR(36)   NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    contact_id         VARCHAR(36)   NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    campaign_id        VARCHAR(36),
    source_call_id     VARCHAR(36),
    score              INTEGER       NOT NULL DEFAULT 0,
    band               VARCHAR(16)   NOT NULL DEFAULT 'LOW',
    status             VARCHAR(32)   NOT NULL DEFAULT 'NEW',
    score_signals      VARCHAR(512),
    requirement        VARCHAR(1024),
    budget             VARCHAR(128),
    timeline           VARCHAR(128),
    is_decision_maker  BOOLEAN,
    owner_user_id      VARCHAR(36)   REFERENCES users(id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ   NOT NULL,
    updated_at         TIMESTAMPTZ   NOT NULL
);
CREATE INDEX idx_lead_org ON leads(organization_id);
CREATE INDEX idx_lead_contact ON leads(contact_id);

-- ---------------------------------------------------------------------------
-- Campaigns
-- ---------------------------------------------------------------------------

CREATE TABLE campaigns (
    id                  VARCHAR(36)  PRIMARY KEY,
    organization_id     VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name                VARCHAR(255) NOT NULL,
    agent_id            VARCHAR(36)  NOT NULL REFERENCES ai_agents(id),
    phone_number_id     VARCHAR(36)  REFERENCES phone_numbers(id) ON DELETE SET NULL,
    state               VARCHAR(32)  NOT NULL DEFAULT 'DRAFT',
    scheduled_start_at  TIMESTAMPTZ,
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    call_window_start   VARCHAR(8)   DEFAULT '10:00',
    call_window_end     VARCHAR(8)   DEFAULT '19:00',
    max_attempts        INTEGER      NOT NULL DEFAULT 3,
    concurrency         INTEGER      NOT NULL DEFAULT 5,
    created_by          VARCHAR(36),
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_campaign_org ON campaigns(organization_id);
CREATE INDEX idx_campaign_state ON campaigns(organization_id, state);

-- Aggregate campaign metrics are derived from these rows rather than kept as
-- counters, so a retried or corrected attempt cannot leave totals inconsistent.
CREATE TABLE campaign_contacts (
    id               VARCHAR(36) PRIMARY KEY,
    organization_id  VARCHAR(36) NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    campaign_id      VARCHAR(36) NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    contact_id       VARCHAR(36) NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    state            VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempts         INTEGER     NOT NULL DEFAULT 0,
    last_attempt_at  TIMESTAMPTZ,
    next_attempt_at  TIMESTAMPTZ,
    outcome          VARCHAR(32),
    last_call_id     VARCHAR(36),
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_campaign_contact UNIQUE (campaign_id, contact_id)
);
CREATE INDEX idx_camp_contact_state ON campaign_contacts(campaign_id, state);

-- ---------------------------------------------------------------------------
-- Calls and their artifacts
-- ---------------------------------------------------------------------------

CREATE TABLE calls (
    id                     VARCHAR(36) PRIMARY KEY,
    organization_id        VARCHAR(36) NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    agent_id               VARCHAR(36) REFERENCES ai_agents(id) ON DELETE SET NULL,
    -- Version that handled the call, so behaviour stays reproducible after the
    -- agent is edited.
    agent_version          INTEGER,
    campaign_id            VARCHAR(36) REFERENCES campaigns(id) ON DELETE SET NULL,
    contact_id             VARCHAR(36) REFERENCES contacts(id) ON DELETE SET NULL,
    phone_number_id        VARCHAR(36) REFERENCES phone_numbers(id) ON DELETE SET NULL,
    customer_number        VARCHAR(24),
    direction              VARCHAR(16) NOT NULL,
    state                  VARCHAR(32) NOT NULL DEFAULT 'INITIATED',
    outcome                VARCHAR(32),
    started_at             TIMESTAMPTZ,
    -- Billing meters voice minutes from connected_at, not started_at.
    connected_at           TIMESTAMPTZ,
    ended_at               TIMESTAMPTZ,
    duration_seconds       INTEGER     NOT NULL DEFAULT 0,
    language               VARCHAR(16),
    provider_call_id       VARCHAR(128),
    transferred_to_user_id VARCHAR(36) REFERENCES users(id) ON DELETE SET NULL,
    transfer_reason        VARCHAR(255),
    recording_enabled      BOOLEAN     NOT NULL DEFAULT TRUE,
    talk_ratio             DOUBLE PRECISION,
    lead_score             INTEGER,
    created_at             TIMESTAMPTZ NOT NULL,
    updated_at             TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_call_org ON calls(organization_id);
CREATE INDEX idx_call_state ON calls(organization_id, state);
CREATE INDEX idx_call_started ON calls(organization_id, started_at);
CREATE INDEX idx_call_agent ON calls(organization_id, agent_id);
CREATE INDEX idx_call_campaign ON calls(campaign_id);
CREATE INDEX idx_call_contact ON calls(contact_id);

CREATE TABLE call_participants (
    id               VARCHAR(36)  PRIMARY KEY,
    organization_id  VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    call_id          VARCHAR(36)  NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    role             VARCHAR(32)  NOT NULL,
    participant_ref  VARCHAR(36),
    display_name     VARCHAR(255),
    joined_at        TIMESTAMPTZ,
    left_at          TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_participant_call ON call_participants(call_id);

-- Audio itself lives in object storage; only the key is held here.
CREATE TABLE call_recordings (
    id                VARCHAR(36)   PRIMARY KEY,
    organization_id   VARCHAR(36)   NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    call_id           VARCHAR(36)   NOT NULL UNIQUE REFERENCES calls(id) ON DELETE CASCADE,
    storage_key       VARCHAR(1024) NOT NULL,
    format            VARCHAR(16)   DEFAULT 'mp3',
    size_bytes        BIGINT,
    duration_seconds  INTEGER,
    -- Set from the organization's retention policy (§34).
    expires_at        TIMESTAMPTZ,
    created_at        TIMESTAMPTZ   NOT NULL,
    updated_at        TIMESTAMPTZ   NOT NULL
);

CREATE TABLE call_transcripts (
    id               VARCHAR(36) PRIMARY KEY,
    organization_id  VARCHAR(36) NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    call_id          VARCHAR(36) NOT NULL UNIQUE REFERENCES calls(id) ON DELETE CASCADE,
    language         VARCHAR(16),
    full_text        TEXT,
    engine           VARCHAR(96),
    word_count       INTEGER,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL
);

CREATE TABLE call_messages (
    id               VARCHAR(36) PRIMARY KEY,
    organization_id  VARCHAR(36) NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    call_id          VARCHAR(36) NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    sequence         INTEGER     NOT NULL,
    speaker          VARCHAR(24) NOT NULL,
    content          TEXT        NOT NULL,
    offset_ms        INTEGER,
    sentiment        VARCHAR(16),
    tool_code        VARCHAR(96),
    tool_payload     TEXT,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_message_call ON call_messages(call_id, sequence);

CREATE TABLE call_summaries (
    id                 VARCHAR(36) PRIMARY KEY,
    organization_id    VARCHAR(36) NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    call_id            VARCHAR(36) NOT NULL UNIQUE REFERENCES calls(id) ON DELETE CASCADE,
    summary            TEXT,
    action_items       TEXT,
    objections         TEXT,
    next_follow_up_at  TIMESTAMPTZ,
    model              VARCHAR(96),
    created_at         TIMESTAMPTZ NOT NULL,
    updated_at         TIMESTAMPTZ NOT NULL
);

CREATE TABLE call_sentiments (
    id               VARCHAR(36)      PRIMARY KEY,
    organization_id  VARCHAR(36)      NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    call_id          VARCHAR(36)      NOT NULL UNIQUE REFERENCES calls(id) ON DELETE CASCADE,
    overall          VARCHAR(16)      NOT NULL,
    score            DOUBLE PRECISION,
    positive_ratio   DOUBLE PRECISION,
    neutral_ratio    DOUBLE PRECISION,
    negative_ratio   DOUBLE PRECISION,
    created_at       TIMESTAMPTZ      NOT NULL,
    updated_at       TIMESTAMPTZ      NOT NULL
);

CREATE TABLE call_intents (
    id               VARCHAR(36)      PRIMARY KEY,
    organization_id  VARCHAR(36)      NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    call_id          VARCHAR(36)      NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    intent           VARCHAR(128)     NOT NULL,
    confidence       DOUBLE PRECISION,
    topics           VARCHAR(512),
    is_primary       BOOLEAN          NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ      NOT NULL,
    updated_at       TIMESTAMPTZ      NOT NULL
);
CREATE INDEX idx_intent_call ON call_intents(call_id);
CREATE INDEX idx_intent_org ON call_intents(organization_id, intent);

-- ---------------------------------------------------------------------------
-- Appointments, tasks and notes
-- ---------------------------------------------------------------------------

CREATE TABLE appointments (
    id                  VARCHAR(36)  PRIMARY KEY,
    organization_id     VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    contact_id          VARCHAR(36)  NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    call_id             VARCHAR(36)  REFERENCES calls(id) ON DELETE SET NULL,
    booked_by_agent_id  VARCHAR(36)  REFERENCES ai_agents(id) ON DELETE SET NULL,
    assigned_user_id    VARCHAR(36)  REFERENCES users(id) ON DELETE SET NULL,
    scheduled_at        TIMESTAMPTZ  NOT NULL,
    duration_minutes    INTEGER      NOT NULL DEFAULT 30,
    status              VARCHAR(32)  NOT NULL DEFAULT 'CONFIRMED',
    subject             VARCHAR(512),
    external_event_id   VARCHAR(255),
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_appt_org ON appointments(organization_id);
CREATE INDEX idx_appt_time ON appointments(organization_id, scheduled_at);

CREATE TABLE tasks (
    id                VARCHAR(36)  PRIMARY KEY,
    organization_id   VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    title             VARCHAR(512) NOT NULL,
    description       TEXT,
    contact_id        VARCHAR(36)  REFERENCES contacts(id) ON DELETE CASCADE,
    call_id           VARCHAR(36)  REFERENCES calls(id) ON DELETE SET NULL,
    assigned_user_id  VARCHAR(36)  REFERENCES users(id) ON DELETE SET NULL,
    due_at            TIMESTAMPTZ,
    status            VARCHAR(32)  NOT NULL DEFAULT 'OPEN',
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_task_org ON tasks(organization_id);
CREATE INDEX idx_task_assignee ON tasks(assigned_user_id);

CREATE TABLE notes (
    id               VARCHAR(36) PRIMARY KEY,
    organization_id  VARCHAR(36) NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    contact_id       VARCHAR(36) REFERENCES contacts(id) ON DELETE CASCADE,
    call_id          VARCHAR(36) REFERENCES calls(id) ON DELETE CASCADE,
    author_user_id   VARCHAR(36) REFERENCES users(id) ON DELETE SET NULL,
    body             TEXT        NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_note_org ON notes(organization_id);
CREATE INDEX idx_note_contact ON notes(contact_id);

-- ---------------------------------------------------------------------------
-- Billing
-- ---------------------------------------------------------------------------

CREATE TABLE plans (
    id                        VARCHAR(36) PRIMARY KEY,
    code                      VARCHAR(48) NOT NULL UNIQUE,
    name                      VARCHAR(96) NOT NULL,
    -- Paise. NULL for custom-priced Enterprise.
    monthly_price_minor       BIGINT,
    currency                  VARCHAR(8)  DEFAULT 'INR',
    included_minutes          INTEGER,
    max_agents                INTEGER,
    max_phone_numbers         INTEGER,
    included_storage_gb       INTEGER,
    overage_per_minute_minor  BIGINT,
    active                    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at                TIMESTAMPTZ NOT NULL,
    updated_at                TIMESTAMPTZ NOT NULL
);

CREATE TABLE subscriptions (
    id                        VARCHAR(36)  PRIMARY KEY,
    organization_id           VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    plan_id                   VARCHAR(36)  NOT NULL REFERENCES plans(id),
    status                    VARCHAR(32)  NOT NULL DEFAULT 'TRIALING',
    current_period_start      DATE         NOT NULL,
    current_period_end        DATE         NOT NULL,
    cancel_at_period_end      BOOLEAN      NOT NULL DEFAULT FALSE,
    external_subscription_id  VARCHAR(128),
    created_at                TIMESTAMPTZ  NOT NULL,
    updated_at                TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_sub_org ON subscriptions(organization_id);

-- Append-only. Invoices are computed by summing records in a period, so a
-- usage row is never updated after it is written.
CREATE TABLE usage_records (
    id               VARCHAR(36)      PRIMARY KEY,
    organization_id  VARCHAR(36)      NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    metric           VARCHAR(32)      NOT NULL,
    quantity         DOUBLE PRECISION NOT NULL,
    source_ref       VARCHAR(36),
    recorded_at      TIMESTAMPTZ      NOT NULL,
    cost_minor       BIGINT,
    created_at       TIMESTAMPTZ      NOT NULL,
    updated_at       TIMESTAMPTZ      NOT NULL
);
CREATE INDEX idx_usage_org_period ON usage_records(organization_id, recorded_at);
CREATE INDEX idx_usage_metric ON usage_records(organization_id, metric);

CREATE TABLE invoices (
    id               VARCHAR(36) PRIMARY KEY,
    organization_id  VARCHAR(36) NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    invoice_number   VARCHAR(64) NOT NULL UNIQUE,
    period_start     DATE        NOT NULL,
    period_end       DATE        NOT NULL,
    subtotal_minor   BIGINT      NOT NULL DEFAULT 0,
    tax_minor        BIGINT      NOT NULL DEFAULT 0,
    total_minor      BIGINT      NOT NULL DEFAULT 0,
    currency         VARCHAR(8)  DEFAULT 'INR',
    status           VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    issued_at        TIMESTAMPTZ,
    due_at           TIMESTAMPTZ,
    paid_at          TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_invoice_org ON invoices(organization_id);

CREATE TABLE payments (
    id                   VARCHAR(36)  PRIMARY KEY,
    organization_id      VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    invoice_id           VARCHAR(36)  NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    amount_minor         BIGINT       NOT NULL,
    currency             VARCHAR(8)   DEFAULT 'INR',
    status               VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
    provider             VARCHAR(64),
    provider_payment_id  VARCHAR(128),
    failure_reason       VARCHAR(512),
    created_at           TIMESTAMPTZ  NOT NULL,
    updated_at           TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_payment_invoice ON payments(invoice_id);
CREATE INDEX idx_payment_org ON payments(organization_id);

-- ---------------------------------------------------------------------------
-- Integrations
-- ---------------------------------------------------------------------------

CREATE TABLE integrations (
    id                     VARCHAR(36)  PRIMARY KEY,
    organization_id        VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    type                   VARCHAR(32)  NOT NULL,
    provider               VARCHAR(64)  NOT NULL,
    display_name           VARCHAR(128),
    -- Ciphertext from the platform KMS. Provider secrets are never stored in
    -- plaintext.
    credentials_encrypted  TEXT,
    config                 TEXT,
    active                 BOOLEAN      NOT NULL DEFAULT TRUE,
    last_sync_at           TIMESTAMPTZ,
    created_at             TIMESTAMPTZ  NOT NULL,
    updated_at             TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_integration_org ON integrations(organization_id);

-- Only the SHA-256 digest is stored; the raw key is shown once at creation.
CREATE TABLE api_keys (
    id               VARCHAR(36)  PRIMARY KEY,
    organization_id  VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    label            VARCHAR(128) NOT NULL,
    key_prefix       VARCHAR(32)  NOT NULL,
    key_hash         VARCHAR(128) NOT NULL UNIQUE,
    scopes           VARCHAR(512),
    created_by       VARCHAR(36)  REFERENCES users(id) ON DELETE SET NULL,
    last_used_at     TIMESTAMPTZ,
    revoked_at       TIMESTAMPTZ,
    expires_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_apikey_org ON api_keys(organization_id);
CREATE INDEX idx_apikey_prefix ON api_keys(key_prefix);

CREATE TABLE webhooks (
    id                      VARCHAR(36)   PRIMARY KEY,
    organization_id         VARCHAR(36)   NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    url                     VARCHAR(1024) NOT NULL,
    events                  VARCHAR(1024) NOT NULL,
    signing_secret          VARCHAR(128),
    active                  BOOLEAN       NOT NULL DEFAULT TRUE,
    delivery_success_count  BIGINT        NOT NULL DEFAULT 0,
    delivery_failure_count  BIGINT        NOT NULL DEFAULT 0,
    last_delivery_at        TIMESTAMPTZ,
    created_at              TIMESTAMPTZ   NOT NULL,
    updated_at              TIMESTAMPTZ   NOT NULL
);
CREATE INDEX idx_webhook_org ON webhooks(organization_id);

-- ---------------------------------------------------------------------------
-- Notifications and auditing
-- ---------------------------------------------------------------------------

CREATE TABLE notifications (
    id               VARCHAR(36)  PRIMARY KEY,
    organization_id  VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    -- NULL addresses the whole organization rather than one user.
    user_id          VARCHAR(36)  REFERENCES users(id) ON DELETE CASCADE,
    title            VARCHAR(255) NOT NULL,
    body             TEXT,
    channel          VARCHAR(24)  NOT NULL DEFAULT 'IN_APP',
    severity         VARCHAR(16)  NOT NULL DEFAULT 'INFO',
    target_ref       VARCHAR(36),
    read_at          TIMESTAMPTZ,
    sent_at          TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_notif_org ON notifications(organization_id);
CREATE INDEX idx_notif_user ON notifications(user_id, read_at);

-- Append-only through the application; retention is an out-of-band policy job.
CREATE TABLE audit_logs (
    id               VARCHAR(36)  PRIMARY KEY,
    organization_id  VARCHAR(36)  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    actor_user_id    VARCHAR(36)  REFERENCES users(id) ON DELETE SET NULL,
    actor_label      VARCHAR(255),
    action           VARCHAR(96)  NOT NULL,
    target_type      VARCHAR(64),
    target_ref       VARCHAR(255),
    ip_address       VARCHAR(64),
    user_agent       VARCHAR(512),
    metadata         TEXT,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_audit_org ON audit_logs(organization_id, created_at);
CREATE INDEX idx_audit_actor ON audit_logs(actor_user_id);
